resources:
  - name: repo_res_autosar
    type: GitRepo
    configuration:
      gitProvider: hk_github
      path: harshkumar1/Adaptive-AUTOSAR


pipelines:
  - name: test_repo
    configuration:
      nodePool: default-dynamic-nodepool
    steps:
      - name: docker_build_bash
        type: Bash
        configuration:
          inputResources:
            - name: repo_res_autosar
        execution:
          onExecute:
            - cmake -B ./build -DCMAKE_BUILD_TYPE=Debug
            - cmake --build ./build --config Debug
            - ctest -C Debug