resources:
  - name: repo_res_autosar
    type: GitRepo
    configuration:
      gitProvider: hk_github
      path: harshkumar1/Adaptive-AUTOSAR


pipelines:
  - name: autosar_example
    configuration:
      nodePool: default-dynamic-nodepool
    steps:
      - name: autosar_build_test
        type: Bash
        configuration:
          inputResources:
            - name: repo_res_autosar
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-u20cpp
                tag: '9'
        execution:
          onExecute:
            - cmake -B ./build -DCMAKE_BUILD_TYPE=Debug
            - cmake --build ./build --config Debug
            - ctest -C Debug