valuesFilePath: ./values.yml

resources:
  - name: repo_res_autosar
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.var.gitProvider }}
      path: {{ .Values.var.path }}

pipelines:
  - name: {{ .Values.var.pipelineName }}
    configuration:
      nodePool: {{ .Values.var.nodePool }}
      jfrogCliVersion: '2'
      runtime:
        type: image
        image:
          custom:
            name: {{ .Values.var.customImage }}
            tag: '{{ .Values.var.customImageTag }}'

    steps:
      - name: autosar_build
        type: Bash
        configuration:
          affinityGroup: autosar
          inputResources:
            - name: repo_res_autosar
        execution:
          onExecute:
            - cd $res_repo_res_autosar_resourcePath
            - cmake -B ./build -DCMAKE_BUILD_TYPE=Debug
            - cmake --build ./build --config Debug
            - cp -r ./build $shared_workspace
      - name: autosar_full_matrix_test
        type: Matrix
        stepMode: Bash
        configuration:
          affinityGroup: autosar
          inputSteps: 
            - name: autosar_build
        stepletMultipliers:
          environmentVariables:
            - module: '*'
            - module: '*'
        execution:
          onExecute:
            - cd $shared_workspace/
            - cd ./build
            - echo $module
            - ctest -C Debug --output-junit test_results.xml #-R "regEx"
          onComplete:
            - sleep 120
            - save_tests test_results.xml
