resources:
  - name: repo_res_autosar
    type: GitRepo
    configuration:
      gitProvider: hk_github
      path: harshkumar1/Adaptive-AUTOSAR
  - name: autosar_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: hk_artifactory
      buildName: autosar_example
      buildNumber: ${run_number}

pipelines:
  - name: autosar_example
    configuration:
      nodePool: default-dynamic-nodepool
      runtime:
        type: image
        image:
          custom:
            name: pipelines.jfrog.io/pipelines-runtime-images/pipelines-w19cpp-ckmake
            tag: '1'
    steps:
      - name: autosar_build
        type: Bash
        configuration:
          affinityGroup: autosar
          inputResources:
            - name: repo_res_autosar
          outputResources:
            - name: autosar_build_info
        execution:
          onExecute:
            - cd $res_repo_res_autosar_resourcePath
            - cmake -B ./build -DCMAKE_BUILD_TYPE=Debug
            - cmake --build ./build --config Debug
            - cp -r ./build $shared_workspace
            - add_cache_files ./build autosar_build
      - name: autosar_full_test
        type: Bash
        configuration:
          affinityGroup: autosar
          inputResources:
            - name: autosar_build_info
        execution:
          onExecute:
            - restore_cache_files autosar_build /tmp/
            - ls -l /tmp/
            - cd $shared_workspace/
            - cd ./build
            - ctest -C Debug --output-junit test_results.xml
            - save_tests test_results.xml
      - name: autosar_partial_test
        type: Bash
        configuration:
          affinityGroup: autosar
          inputResources:
            - name: autosar_build_info
        execution:
          onExecute:
            - restore_cache_files autosar_build /tmp/
            - ls -l /tmp/
            - cd $shared_workspace/
            - cd ./build
            - ctest -R 'ArxmlNodeTest*' -C Debug --output-junit test_results.xml
            - save_tests test_results.xml